steps:
- name: Checkout del código
  # Acción que descarga el repositorio.
  uses: actions/checkout@v4
  
- name: Configurar Node.js
  # Acción que instala el entorno de Node.js.
  uses: actions/setup-node@v4
  with:
    # Usa la versión de soporte a largo plazo (LTS).
    node-version: 'lts/*'
    
- name: Instalar dependencias
  # Comando para instalar dependencias de forma limpia y rápida en CI.
  run: npm ci
  
- name: Ejecutar pruebas
  # Comando para correr los tests unitarios.
  run: npm test --silent
